### ISSUE TITLE
Fix concurrency issue with Example

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-android-adapters#11]
The example is using async transactions and there is a race condition that can cause the following exception:

```
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not
                             receive a notification. Make sure the content of your adapter is not modified from a backgr
                            ound thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged(
                            ) when its content changes. [in ListView(2131427408, class android.widget.ListView) with Ada
                            pter(class io.realm.examples.adapters.adapter.MyListAdapter)]
```

Not entirely sure why this is happening as the only one modifying the last is the BaseAdapter on the UI thread 😒. Can only trigger this using `./gradlew monkeyDebug`

**Comment by nhachicha** [comment]
I think the problem is here https://github.com/realm/realm-android-adapters/blob/02af33a547b136d90129362fb46401df518443cd/example/src/main/java/io/realm/examples/adapters/MainActivity.java#L61

this will have an impact on the `getCount` here http://androidxref.com/6.0.1_r10/xref/frameworks/base/core/java/android/widget/ListView.java#1572

I think the element will be deleted, before we get the change to get the `RealmChangeListener` that will call `notifyDataSetChange`, making the `getCount` to be inconsistent with the value previously stored [onAttachWindow] (http://androidxref.com/6.0.1_r10/xref/frameworks/base/core/java/android/widget/AbsListView.java#2874) hence the exception, using an integration test that delays the `RealmChangeListener` could be a start to try to reproduce the issue

**Comment by berbschloe** [comment]
I was able to reproduce this roughly accurately in the example by:
-Adding about 30 items to the list
-Scrolling to the bottom
-Long press to delete an item
-Scroll up as soon as (or right before the item deletes)
The scrolling between the data update and the realm results causes the IllegalStateException to occur.
I hope this helps :)

**Comment by xprimes** [comment]
I have the same problem here ,did anybody has solution?

**Comment by berbschloe** [comment]
I have not been able to reproduce this with RecyclerView, it could be a quick viable alternative.

**Comment by xprimes** [comment]
Thanks @berbschloe , 
In my situation , I did not reproduce this problem until I  upgrade the realm from version 0.88.3 to 1.0.

**Comment by xprimes** [comment]
Hello @cmelchior , do you have  schedule to fix this crash? 
Thank you.

**Comment by cmelchior** [comment]
@xprimes Yes, it will be fixed by this https://github.com/realm/realm-java/pull/2926.

**Comment by cmelchior** [comment]
This have been fixed by https://github.com/realm/realm-java/pull/2990 which will be part of 1.0.1
