### ISSUE TITLE
Add support for RecyclerView animations

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-android-adapters#21]
With 1.1.0 basic support for RecyclerViews where added. However that adapter only calls `notifyDataSetChanged` which means that all the animations supported by RecyclerView are not used.

We should add support for all the animation methods

```
final void  notifyItemChanged(int position)
final void  notifyItemChanged(int position, Object payload)
final void  notifyItemInserted(int position)
final void  notifyItemMoved(int fromPosition, int toPosition)
final void  notifyItemRangeChanged(int positionStart, int itemCount)
final void  notifyItemRangeChanged(int positionStart, int itemCount, Object payload)
final void  notifyItemRangeInserted(int positionStart, int itemCount)
final void  notifyItemRangeRemoved(int positionStart, int itemCount)
final void  notifyItemRemoved(int position)
```

This requires https://github.com/realm/realm-java/issues/989 being completed first.

**Comment by Zhuinden** [comment]
If a previous version of the list is pinned and a new version is synced, then the newly added `[DiffUtil](https://developer.android.com/reference/android/support/v7/util/DiffUtil.html)` could evaluate the difference between two `RealmResults`. But this would need the ability to pin the UI thread's RealmResults for the previous version, and retain objects that are "no longer valid" while the calculation is in progress.

**Comment by oantajames** [comment]
Is this implemented in the new Realm release ? Thanks!

**Comment by oantajames** [comment]
@Zhuinden  Than for the reply! Is there a way I can trigger notifyItemChanged so I can use item animations in a Recycler view that uses Realm ? Thanks in advance!

**Comment by Zhuinden** [comment]
@oantajames I've been thinking a **lot** about how it would be done without the Results integration, but it'd involve either copying or UI-thread synchronous writes, and both of those are bad - so I'm not sure what can be done unless Realm explicitly notifies you of the exact changes. 😕

**Comment by oantajames** [comment]
@Zhuinden  Thanks again! ohh man. Will need to change from realm then with something else that supports animations...

**Comment by Zhuinden** [comment]
@oantajames okay, so technically it's not **impossible**, but you'll lose auto-updates / zero-copy.

A possibility is copying the result set entirely as a List to have the previous version, and on change you'd copy the new version, and **then** with unmanaged lists you can call `DiffUtil` provided by the support library.

However, this means you would create unmanaged copies of the entire dataset so that you can also calculate a difference between them.

It's the reason why I personally am waiting for the Results integration, it'll bring in a lot of cool stuff 😄

**Comment by oantajames** [comment]
@Zhuinden thanks for the help! Will check in a few months to see if they updated the support for the animations. Until then I will need to switch. Thanks again 👍 😄

**Comment by consp1racy** [comment]
https://github.com/realm/realm-java/issues/4079

**Comment by Zhuinden** [comment]
Isn't this fixed by 2.0.0 and https://github.com/realm/realm-android-adapters/pull/83 ?

**Comment by cmelchior** [comment]
Yes, it was. I believe what @consp1racy is asking for is fine-grained notifications for _each_ individual object, i.e. instead of just knowing that it changed, it should also specify exactly how.

Our current thinking around is that we want to implement Single Object Notifications first (https://github.com/realm/realm-java/issues/4101), which will provide this information. It is annoying to setup for all elements in a `RealmResults` , but e.g a RecyclerView would redraw the entire index anyway, so the information about what exactly changed isn't _that_ useful. Granted, there could be other use cases.

@consp1racy Can you elaborate on exactly what you need this information for?

**Comment by consp1racy** [comment]
@cmelchior Yes, fine-fine-grained notifications :D

`RecyclerView.Adapter#notifyItem(Range)Changed` without payload triggers crossfade animation on the whole item. This is especially noticable when large continuous portions of the item *don't* change.

![screenshot_2017-03-09-14-06-26](https://cloud.githubusercontent.com/assets/4589773/23751480/db1bf360-04d1-11e7-8a6a-1f0b15f82a83.png)

Example changes:
 * Suppose only checked state of the `Switch` changed.

Current result:
 * The whole item crossfades.

Expected result:
 * The card frame + background doesn't fade.
 * The map doesn't fade (large images especially may conserve resources).
 * The text stays the same.
 * Right hand side button stays the same.
 * Only the `Switch` state updates because that's the only thing that changed.

The expected result of course needs work on consumer side - analyzing the list of changed fields and reacting accordingly. However currently there's no such list which means falling back to complete crossfade.

Other than UI I know of no useful applications of observing differences.

**Comment by cmelchior** [comment]
Thank you @consp1racy . That is actually a pretty valid use case. We will have to think about this a little bit though as payloads only makes sense for relatively small lists. Calculating diffs for very long lists would probably be too expensive.

**Comment by cmelchior** [comment]
Since this would need to be solved on the Realm-Java side of things, I'm closing this issue here. I created https://github.com/realm/realm-java/issues/4305 instead to track the relevant changes required.

**Comment by consp1racy** [comment]
Because this is potentially heavy workload and useful only in the UI (or this Adapter even) you may want to solve it in this project instead. Or make it an opt-in feature in realm-java.

---

In any case until this is supported natively, the RealmRecyclerViewAdapter could work around this by creating a snapshot after processing a change and comparing next update against this snapshot (using DiffUtils).

This solution would be less effective than current implementation BUT
* it would be complete 
* and it would be no more expensive than solutions without realm where the adapter holds a sort of snapshot anyway.

@cmelchior What do you think about this?

**Comment by Zhuinden** [comment]
The adapter doesn't hold a snapshot though, and objects inside snapshot collections still get invalidated. 

So the only way to remember an old version of the Realm is via `copyFromRealm` which copies all data out entirely to an unmanaged object, which is memory heavy and kinda slow-ish.

Imo, version pinning wouldn't be such an issue if Realm didn't rely entirely on GC to kill results that have no references, although I wonder how much more effective the finalizer daemon is in comparison.

**Comment by consp1racy** [comment]
Which items in the snapshot get invalidated (and when)? If only the removed items were invalidated and the changed remained valid we could just access these with the help of `OrderedCollectionChangeSet.getChanges()`.

**Comment by Zhuinden** [comment]
Yeah, removed objects are invalidated.

**Comment by cmelchior** [comment]
@consp1racy Copying data out and using `DiffUtil` is a valid option, but then there would be no need for a `RealmRecyclerViewAdapter`, so that isn't something we are going to implement.
